
package Libreria_Personajes;

/**
 *
 * @author Luigi Gomigi
 */
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;

public class LibreriaVisual_Lookandfeel extends javax.swing.JFrame {

    /**
     * Creates new form LibreriaVisual_Lookandfeel
     */
    public LibreriaVisual_Lookandfeel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Establecer el aspecto visual de la interfaz utilizando Nimbus Look and Feel
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | UnsupportedLookAndFeelException e) {
        }
        
        // Crear una ventana
        JFrame frame = new JFrame("Personajes de Videojuegos");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(1200, 400);
        frame.setLayout(new FlowLayout()); // Diseño de flujo

        // Mensaje de bienvenida
        String mensajeBienvenida = "Bienvenido: Por favor, escoge tu personaje";
        JButton mensajeButton = new JButton(mensajeBienvenida);
        mensajeButton.setEnabled(false); // Deshabilitar el botón
        mensajeButton.setFont(new Font("Arial", Font.BOLD, 34)); // Configurar la fuente
        frame.getContentPane().add(mensajeButton);

        
        // Panel para los botones
        JPanel buttonPanel = new JPanel();
        buttonPanel.setBackground(new Color(240, 240, 240)); // Color de fondo del panel
        frame.getContentPane().add(buttonPanel);

        // Personajes
        String[] personajes = {"Mario Bros", "Link de Zelda", "Ale Peach", "Solid Snake", "Kratos",
                "Sonic", "Donkey Kong", "Wesker", "Kirby", "Luigi Gomigi"};

        // Crear los botones de personajes
        for (String personaje : personajes) {
            JButton button = new JButton("Personaje ?");
            button.setBackground(new Color(204, 229, 255)); // Color de fondo del botón
            button.addActionListener((e) -> {
                JOptionPane.showMessageDialog(null, "Escogiste al personaje: " + personaje);
            });
            buttonPanel.add(button);
        }

        // Centrar la ventana en la pantalla
        frame.setLocationRelativeTo(null);

        // Mostrar la ventana
        frame.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibreriaVisual_Lookandfeel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibreriaVisual_Lookandfeel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibreriaVisual_Lookandfeel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibreriaVisual_Lookandfeel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibreriaVisual_Lookandfeel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
